default:
  tags:
    - master
  
variables:
    GIT_STRATEGY: none

stages:
  - update

job-build:
  stage: update
  needs: []
  variables:
    MAVEN_OPTS: --enable-preview
  script:
    - cd ~/nowbot
    - git fetch --all
    - git reset --hard origin/master
    - git pull
    - git lfs pull
    - mvn clean
    - mvn package

job-update:
  stage: update
  needs: 
    - job-build
  script:
    - cd ~/nowbot
    - mv ~/nowbot/target/nowbot-linux.jar ~/work
    - sudo systemctl restart nowbot