package com.now.nowbot.model.enums

enum class LazerModType(@JvmField val value: Int, @JvmField val acronym: String) {
    None(0, ""),
    NoMod(0, "NM"),
    NoFail(1, "NF"),
    Easy(1 shl 1, "EZ"),
    TouchDevice(1 shl 2, "TD"), // 替换未使用的 No Video
    Hidden(1 shl 3, "HD"),
    HardRock(1 shl 4, "HR"),
    SuddenDeath(1 shl 5, "SD"),
    DoubleTime(1 shl 6, "DT"),
    Relax(1 shl 7, "RX"),
    HalfTime(1 shl 8, "HT"),
    Nightcore((1 shl 9) + (DoubleTime.value), "NC"), // 总是和 DT 一起使用 : 512 + 64 = 576
    Flashlight(1 shl 10, "FL"),
    Autoplay(1 shl 11, "AT"),
    SpunOut(1 shl 12, "SO"),
    Autopilot(1 shl 13, "AP"),
    Perfect(1 shl 14, "PF"),
    Key4(1 shl 15, "4K"),
    Key5(1 shl 16, "5K"),
    Key6(1 shl 17, "6K"),
    Key7(1 shl 18, "7K"),
    Key8(1 shl 19, "8K"),
    FadeIn(1 shl 20, "FI"),
    Random(1 shl 21, "RD"),
    Cinema(1 shl 22, "CM"),
    TargetPractice(1 shl 23, "TP"),
    Key9(1 shl 24, "9K"),
    KeyCoop(1 shl 25, "CP"),
    Key1(1 shl 26, "1K"),
    Key3(1 shl 27, "3K"),
    Key2(1 shl 28, "2K"),
    ScoreV2(1 shl 29, "V2"),
    Mirror(1 shl 30, "MR"), // mania 可以上传成绩
    KeyMod(521109504, "NK"),
    FreeMod(522171579, "FM"),
    ScoreIncreaseMods(1049688, "IM"),
    Other(-1, "??"),
    // 以下是 Lazer 独占的可以上传成绩的模组
    Daycore(-1, "DC"),
    Blinds(-1, "BL"),
    Cover(-1, "CO"),
    StrictTracking(-1, "ST"),
    AccuracyChallenge(-1, "AC"),
    DifficultyAdjust(-1, "DA"),
    Traceable(-1, "TC"),
    WindUp(-1, "WU"),
    WindDown(-1, "WD"),
    AdaptiveSpeed(-1, "AS"),
    Muted(-1, "MU"),
    NoScope(-1, "NS"),
}
