botfile:
  # 基目录
  root: /tmp/bot-package-test

# 测试数据源
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-test-query: SELECT 1;
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  proxy:
    port: 0
