botfile:
  # 基目录
  root: /tmp/bot-package-test

# 测试数据源
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:14123/db_test
    username: test
    password: 4z3kk68x2
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-test-query: SELECT 1;
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  proxy:
    port: 0
