#服务监听端口
server:
  port: 8388
#botfile 程序的运行路径
botfile:
  root: C:/bot #您想运行的位置
  bind: ${botfile.root}bind/
  mirai: ${botfile.root}
  bgdir: ${botfile.root}bg/
  font: ${botfile.root}font/
  imgbuffer: ${botfile.root}imgbuffer/
  osuid: ${botfile.root}Id/
#数据源
spring:
  profiles:
    include:
      QQ,OSU
#使用SQLite小型数据库
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-test-query: SELECT version()
#使用MySql数据库
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://{路径}:{端口}/{库}?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC&useSSL=true
#    username:
#    password:
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 1
  #jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
shiro:
  ws-config:
    # 反向 Websocket 连接地址，无需该配置字段可删除，将使用默认值 "/ws/shiro"
    ws-url: "/websocket-1"
    # 访问密钥，强烈推荐在公网的服务器设置
    # 超时回收，默认10秒
    timeout: 10
    # 二进制消息的最大长度
    max-binary-message-buffer-size: 512000
    # 最大空闲时间，超过这个时间将关闭会话
    max-session-idle-timeout: 900000
    # 最大文本消息缓冲区
    max-text-message-buffer-size: 512000

#log配置,可有可无,只是位置,详细设定请写在 logback.xml
logging:
  file:
    name: ${botfile.root}botlog/bot.log
